# Generated by Django 4.2 on 2023-04-28 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection", options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="customer", options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(name="product", options={"ordering": ["title"]},),
        migrations.AlterField(
            model_name="product",
            name="promotions",
            field=models.ManyToManyField(blank=True, to="store.promotion"),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
