# Generated by Django 4.2 on 2023-05-23 17:26

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="store/images",
                validators=[store.validators.validate_file_size],
            ),
        ),
    ]
