# Generated by Django 4.2 on 2023-05-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_collection_featured_product_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
